细化文档
xuperchain/docs pull request #231
Opened 2022-04-15 07:04 UTC by uaanaa

**快速入门/环境部署**
- 目录表
  - 根据 v5.1 实际编译结果调整 config 目录为 genesis 目录.
  - 对 blockchain、logs、tmp 等目录增加说明：启动链之后生成.

**快速入门/基本操作**
- 创建账号
  - 普通账号创建增加国密相关引导.
  - 合约账号创建增加 xchain 返回结果，与普通账号创建保持一致.

- 查询资源余额  
  - 命令与描述对应，增加命令中的端口号.
  - 新增查询合约账户余额命令.

- 转账
  - 新增注解，解释默认扣款账户与默认账户的预分配

2022-04-15 08:47 UTC, chenfengjin requested changes

2022-04-15 08:47 UTC, chenfengjin commented on source/quickstart/quickstart.rst
> +    给到该账户，具体可以参考 data/genesis/xuper.json
这里为什么需要换行呢?

2022-04-15 08:47 UTC, chenfengjin commented on source/quickstart/quickstart.rst
> +    $ bin/xchain-cli account balance --keys data/keys -H 127.0.0.1:37101
--keys 路径和注释一致

2022-04-15 08:49 UTC, uaanaa commented on source/quickstart/quickstart.rst
> +    给到该账户，具体可以参考 data/genesis/xuper.json
写错嘞，改一下

2022-04-15 08:49 UTC, uaanaa commented on source/quickstart/quickstart.rst
> +    $ bin/xchain-cli account balance --keys data/keys -H 127.0.0.1:37101
haode

2022-04-22 03:41 UTC, chenfengjin approved these changes

2022-04-22 03:42 UTC, merged